/**
 * ---------------------------------------------------------------------------------
 * This file was automatically generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 * ---------------------------------------------------------------------------------
 */

export type SanityImagePalette = {
  _type: "sanity.imagePalette"
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch"
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions"
  height?: number
  width?: number
  aspectRatio?: number
}

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot"
  x?: number
  y?: number
  height?: number
  width?: number
}

export type SanityImageCrop = {
  _type: "sanity.imageCrop"
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityFileAsset = {
  _id: string
  _type: "sanity.fileAsset"
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: "sanity.imageAsset"
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
}

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata"
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type Geopoint = {
  _type: "geopoint"
  lat?: number
  lng?: number
  alt?: number
}

export type Slug = {
  _type: "slug"
  current: string
  source?: string
}

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: "span"
        _key: string
      }>
      style?: "normal" | "h2" | "h3" | "h4" | "blockquote"
      listItem?: "bullet" | "number"
      markDefs?: Array<{
        href?: string
        _type: "link"
        _key: string
      }>
      _type: "block"
      _key: string
    }
  | {
      asset?: {
        _ref: string
        _type: "reference"
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset"
      }
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: "image"
      _key: string
    }
>

export type Resource = {
  _type: "resource"
  type: "pdf" | "link" | "repo" | "code" | "slides"
  title: string
  description?: string
  url: string
}

export type LearningOutcome = {
  _type: "learningOutcome"
  icon?: string
  title: string
  description: string
}

export type Module = {
  _type: "module"
  title: string
  summary?: string
  lessons: Array<{
    _ref: string
    _type: "reference"
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: "lesson"
  }>
}

export type Category = {
  _id: string
  _type: "category"
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  description?: string
}

export type Instructor = {
  _id: string
  _type: "instructor"
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  slug: Slug
  photo?: {
    asset?: {
      _ref: string
      _type: "reference"
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset"
    }
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
  }
  expertise?: Array<string>
  bio?: BlockContent
}

export type Lesson = {
  _id: string
  _type: "lesson"
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  videoUrl: string
  thumbnail?: {
    asset?: {
      _ref: string
      _type: "reference"
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset"
    }
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
  }
  duration: number
  freePreview?: boolean
  studentCount?: number
  notes?: BlockContent
  keyPoints?: Array<string>
  proTip?: string
  resources?: Array<Resource>
}

export type Course = {
  _id: string
  _type: "course"
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  summary: string
  coverImage: {
    asset?: {
      _ref: string
      _type: "reference"
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset"
    }
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt: string
  }
  level: "beginner" | "intermediate" | "advanced"
  price: number
  popular?: boolean
  studentCount?: number
  learningOutcomes?: Array<LearningOutcome>
  instructor: {
    _ref: string
    _type: "reference"
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: "instructor"
  }
  category: {
    _ref: string
    _type: "reference"
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: "category"
  }
  modules: Array<Module>
}

export declare const internalGroqTypeReferenceTo: unique symbol

// Query Result Types

export type COURSES_LIST_QUERYResult = Array<{
  _id: string
  title: string
  slug: string
  summary: string
  coverImage: Course["coverImage"]
  level: Course["level"]
  price: number
  popular: boolean | null
  studentCount: number | null
  instructor: {
    _id: string
    name: string
    slug: string
    photo: Instructor["photo"]
  } | null
  category: {
    _id: string
    title: string
    slug: string
  } | null
  moduleCount: number
  totalDuration: number | null
}>

export type COURSE_SLUGS_QUERYResult = Array<{
  slug: string
}>

export type COURSE_BY_SLUG_QUERYResult = {
  _id: string
  title: string
  slug: string
  summary: string
  coverImage: Course["coverImage"]
  level: Course["level"]
  price: number
  popular: boolean | null
  studentCount: number | null
  learningOutcomes: Array<{
    _key: string
    icon: string | null
    title: string
    description: string
  }> | null
  instructor: {
    _id: string
    name: string
    slug: string
    photo: Instructor["photo"]
    expertise: Array<string> | null
    bio: BlockContent | null
  } | null
  category: {
    _id: string
    title: string
    slug: string
    description: string | null
  } | null
  modules: Array<{
    _key: string
    title: string
    summary: string | null
    lessons: Array<{
      _id: string
      title: string
      slug: string
      duration: number
      freePreview: boolean | null
      studentCount: number | null
      thumbnail: Lesson["thumbnail"]
    }> | null
  }>
  totalDuration: number | null
} | null

export type LESSON_SLUGS_QUERYResult = Array<{
  slug: string
}>

export type LESSON_BY_SLUG_QUERYResult = {
  _id: string
  title: string
  slug: string
  videoUrl: string
  thumbnail: Lesson["thumbnail"]
  duration: number
  freePreview: boolean | null
  studentCount: number | null
  notes: BlockContent | null
  keyPoints: Array<string> | null
  proTip: string | null
  resources: Array<{
    _key: string
    type: Resource["type"]
    title: string
    description: string | null
    url: string
  }> | null
  course: {
    _id: string
    title: string
    slug: string
    modules: Array<{
      _key: string
      title: string
      summary: string | null
      lessons: Array<{
        _id: string
        title: string
        slug: string
      }> | null
    }>
  } | null
} | null

export type INSTRUCTORS_LIST_QUERYResult = Array<{
  _id: string
  name: string
  slug: string
  photo: Instructor["photo"]
  expertise: Array<string> | null
  bio: BlockContent | null
}>

export type INSTRUCTOR_BY_SLUG_QUERYResult = {
  _id: string
  name: string
  slug: string
  photo: Instructor["photo"]
  expertise: Array<string> | null
  bio: BlockContent | null
  courses: Array<{
    _id: string
    title: string
    slug: string
    summary: string
    coverImage: Course["coverImage"]
    level: Course["level"]
    price: number
    popular: boolean | null
    studentCount: number | null
    moduleCount: number
    totalDuration: number | null
  }>
} | null

export type CATEGORIES_LIST_QUERYResult = Array<{
  _id: string
  title: string
  slug: string
  description: string | null
}>
